---
name: Build Tool

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          cache-dependency-path: ${{ github.workspace }}/go.sum
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: build --snapshot --clean
